version: 1.0.{build}
environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true
  NUGET_SOURCE: https://www.nuget.org/api/v2/package
  GITHUB_USERNAME: sushihangover
  GITHUB_TOKEN:
    secure: mMrrEYoa3W9aMdthNtjHA9+FfEoYc3rcg7QW2lqvjZQ=
  NUGET_APIKEY:
    secure: h3kfW8Xw3qPqhB3vM3X9oxBSzx1DWYoTXO7taAo+Ig33qmEcl43XUBaqNumUze4N
build_script:
- ps: ./build.ps1 -Verbosity Diagnostic
test: off
artifacts:
- path: artifacts/*
